specVersion: 0.2.0
name: finitestate
version: 0.0.4
description: This SubQuery project can be use as a st...
repository: https://github.com/RyuH1/fst_sq
schema:
  file: ./schema.graphql
network:
  endpoint: wss://fs-api.ata.network
  genesisHash: '0x19757b969097d71a154bb26493078f179a8dec1dd9c75bd9d4586d38c659064e'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
